ARCHS = armv6 armv7 arm64
TARGET = iphone:clang:12.2:11.2

include /opt/theos/makefiles/common.mk
TWEAK_NAME = c0mebackf0lders

c0mebackf0lders_FILES = Tweak.x
c0mebackf0lders_EXTRA_FRAMEWORKS += Cephei

include /opt/theos/makefiles/aggregate.mk